[build]
  command = "cd front && npm install && npm run build"
  publish = "front/dist"

[build.environment]
  NODE_VERSION = "20.19.0"
  VITE_API_BASE_URL = "https://handloom-fashion-fsda.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://handloom-fashion-fsda.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
